import js from "@eslint/js";
import globals from "globals";

export default [
  js.configs.recommended,
  {
    files: ["web/static/js/**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      globals: {
        ...globals.browser,
        globalDevices: "writable",
        globalGroups: "writable",
        globalVendors: "writable",
        globalVersions: "writable",
        currentLang: "writable",
        currentRole: "writable",
        currentUser: "writable",
        appLoading: "writable",
        i18n: "writable",
        _locView: "writable",
        _pingRefreshTimer: "writable",
        _activeSubnetScanJob: "writable",
        vis: "readonly",
        html2pdf: "readonly",
        apiFetch: "readonly",
        escapeHtml: "readonly",
        showToast: "readonly",
        switchTab: "readonly",
        appInit: "readonly",
        renderDeviceTable: "readonly",
        renderGroupsTable: "readonly",
        loadSnmpDefaults: "readonly",
        populateProvisioningFormSelects: "readonly",
        loadProvisioningTab: "readonly",
        loadHome: "readonly",
        loadTopology: "readonly",
        loadInteractiveMap: "readonly",
        loadCategoriesData: "readonly",
        loadThreatIntel: "readonly",
        locSwitchView: "readonly",
        loadConfigAnalyzer: "readonly",
        loadAiTab: "readonly",
        loadUsers: "readonly",
        loadSites: "readonly",
        loadMcpTab: "readonly",
        loadMcpClientTab: "readonly",
        loadFgtTab: "readonly",
        loadWlcTab: "readonly",
        loadAuditChecklistTab: "readonly",
        loadAppSettings: "readonly",
        flowsTabShown: "readonly",
        loadIncidentsTab: "readonly",
        loadRedundancyTab: "readonly",
        loadNetSecAuditTab: "readonly",
        startTriageStatusPolling: "readonly",
        openCliModal: "readonly",
        openSubnetScanModal: "readonly",
        editDevice: "readonly",
        deleteDevice: "readonly",
        pingSingleDevice: "readonly",
        triageSingleDevice: "readonly",
        renameDevice: "readonly",
        downloadBackup: "readonly",
        renameGroup: "readonly",
        deleteGroup: "readonly",
      },
    },
    rules: {
      "no-redeclare": ["error", { "builtinGlobals": false }],
      "no-duplicate-imports": "error",
      "no-unreachable": "error",
      "no-unused-vars": "off",
      "no-undef": "off",
      "no-empty": ["error", { "allowEmptyCatch": true }],
      "no-constant-condition": "warn",
    },
  },
  {
    ignores: [
      "node_modules/**",
      "web/static/vendor/**",
      "dist/**",
      "data/**",
    ],
  },
];
